# Generated by Django 4.1.2 on 2022-10-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='japplient',
            fields=[
                ('japplient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('japplient_edu', models.CharField(max_length=50)),
                ('japplient_mobile', models.IntegerField()),
                ('japplient_user', models.IntegerField()),
            ],
        ),
    ]
