# Generated by Django 4.1.2 on 2022-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_emal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.IntegerField(),
        ),
    ]
