# Generated by Django 4.1.2 on 2022-10-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0002_alter_user_user_emal_alter_user_user_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
